# Generated by Django 4.1.5 on 2023-01-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, verbose_name='Название')),
                ('description', models.CharField(db_index=True, max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='gift_image/%Y/%m/%d', verbose_name='Картинка')),
                ('blocked_until', models.DateTimeField(auto_now=True, verbose_name='Заблокировано до (дата)')),
            ],
            options={
                'verbose_name': 'Призы',
                'verbose_name_plural': 'Призы',
                'ordering': ('name',),
            },
        ),
    ]
