# Generated by Django 4.1.5 on 2023-01-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='blocked_until',
            field=models.DateTimeField(verbose_name='Заблокировано до (дата)'),
        ),
    ]
