# Generated by Django 4.1.5 on 2023-01-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_gifts_blocked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='complete',
            field=models.DateTimeField(null=True, verbose_name='Завершиться'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='blocked_until',
            field=models.DateTimeField(verbose_name='Заблокировано до'),
        ),
    ]
