# Generated by Django 4.1.5 on 2023-01-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_gifts_complete_alter_gifts_blocked_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifts',
            old_name='complete',
            new_name='complete_until',
        ),
    ]
