# Generated by Django 4.1.5 on 2023-01-15 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_category_quests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quests',
            options={'ordering': ('reward',), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(db_index=True, default='#ffffff', max_length=30, verbose_name='Цвет(HEX)'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='complexity',
            field=models.SmallIntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='reward',
            field=models.SmallIntegerField(verbose_name='Награда'),
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpoints', to='Home.quests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
