# Generated by Django 4.1.5 on 2023-01-15 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0006_alter_quests_options_alter_category_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.IntegerField(verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpoints', to='Home.quests', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
