# Generated by Django 4.1.5 on 2023-01-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_userpoints_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_tasks', to='Home.quests'),
        ),
    ]
