# Generated by Django 4.1.5 on 2023-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_userpoints_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='quest',
        ),
        migrations.AddField(
            model_name='userpoints',
            name='quests_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to='Home.quests', verbose_name='Выполненные задания'),
        ),
    ]
