# Generated by Django 4.1.5 on 2023-01-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_userpoints_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='quests_completed',
            field=models.ManyToManyField(blank=True, null=True, related_name='quests_completed', to='Home.quests', verbose_name='Выполненные задания'),
        ),
    ]
