# Generated by Django 4.1.5 on 2023-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_userpoints_quests_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='quests_completed',
            field=models.ManyToManyField(blank=True, null=True, related_name='quests_complete', to='Home.quests', verbose_name='Выполненные задания'),
        ),
    ]
