# Generated by Django 4.1.5 on 2023-01-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0013_alter_userpoints_quests_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quests_completed', models.ManyToManyField(blank=True, null=True, to='Home.quests', verbose_name='Выполненные задания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выполненные задания',
                'verbose_name_plural': 'Выполненное задание',
            },
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
