# Generated by Django 4.1.5 on 2023-01-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_userquests_quest_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='amount_available_user',
            field=models.SmallIntegerField(default=1, verbose_name='Количество доступное для пользователя'),
        ),
    ]
