# Generated by Django 4.1.5 on 2023-01-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='quests',
            name='user_completion',
            field=models.SmallIntegerField(default=0, verbose_name='Выполнено пользователем'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
