# Generated by Django 4.1.5 on 2023-02-02 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0020_remove_quests_user_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom_quest', models.BooleanField(default=False, verbose_name='Сделать кастомный предмет')),
                ('custom_quest', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Награда')),
                ('custom_reward', models.SmallIntegerField(db_index=True, null=True, verbose_name='Награда')),
                ('quest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.quests', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Предметы рулетки',
                'verbose_name_plural': 'Предметы рулетки',
                'ordering': ('quest__reward',),
            },
        ),
        migrations.CreateModel(
            name='RouletteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Выполнено')),
                ('completed_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.rouletteitems', verbose_name='Выполненное задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ('completed_at',),
            },
        ),
    ]
