# Generated by Django 4.1.5 on 2023-02-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_remove_quests_user_completion'),
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roulettehistory',
            options={'ordering': ('completed_at',), 'verbose_name': 'История рулетки', 'verbose_name_plural': 'История рулетки'},
        ),
        migrations.RemoveField(
            model_name='rouletteitems',
            name='custom_quest',
        ),
        migrations.AddField(
            model_name='rouletteitems',
            name='custom_title',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Кастомное название'),
        ),
        migrations.AlterField(
            model_name='rouletteitems',
            name='custom_reward',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Кастомная награда'),
        ),
        migrations.AlterField(
            model_name='rouletteitems',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.quests', verbose_name='Задание'),
        ),
    ]
