# Generated by Django 4.1.5 on 2023-02-02 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roulette', '0002_alter_roulettehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spin', models.SmallIntegerField(db_index=True, default=0, verbose_name='Всего прокручено')),
                ('total_completed_quest', models.SmallIntegerField(default=0, verbose_name='Всего выполненных заданий')),
                ('total_not_completed_quest', models.SmallIntegerField(default=0, verbose_name='Всего выполненных заданий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя рулетка',
                'verbose_name_plural': 'Профиль пользователя рулетка',
            },
        ),
    ]
