# Generated by Django 4.1.5 on 2023-02-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_rouletteuserprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rouletteuserprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профиль пользователя'},
        ),
        migrations.AddField(
            model_name='roulettehistory',
            name='is_completed_quest',
            field=models.BooleanField(default=False, verbose_name='Задание выполнено'),
        ),
        migrations.AlterField(
            model_name='roulettehistory',
            name='completed_quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roulette.rouletteitems', verbose_name='Задание'),
        ),
    ]
