# Generated by Django 4.1.5 on 2023-02-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_remove_quests_user_completion'),
        ('roulette', '0004_alter_rouletteuserprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rouletteuserprofile',
            name='quest_in_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.quests', verbose_name='Выполняемое задание'),
        ),
    ]
