# Generated by Django 4.1.5 on 2023-02-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_rouletteuserprofile_quest_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='rouletteitems',
            name='custom_color',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Кастомный цвет'),
        ),
    ]
