# Generated by Django 4.1.5 on 2023-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0006_rouletteitems_custom_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='rouletteitems',
            name='custom_description',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Кастомное описание'),
        ),
    ]
