# Generated by Django 4.1.5 on 2023-02-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0007_rouletteitems_custom_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roulettehistory',
            name='is_completed_quest',
        ),
    ]
