# Generated by Django 4.1.5 on 2023-02-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0008_remove_roulettehistory_is_completed_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettehistory',
            name='completed_stage',
            field=models.SmallIntegerField(choices=[(0, 'Выполняется'), (1, 'Провалено'), (2, 'Выполнено')], default=0, verbose_name='Сложность'),
        ),
    ]
