# Generated by Django 4.1.5 on 2023-02-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0009_roulettehistory_completed_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulettehistory',
            name='completed_stage',
            field=models.SmallIntegerField(choices=[(0, 'Выполняется'), (1, 'Провалено'), (2, 'Выполнено')], default=0, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='rouletteuserprofile',
            name='quest_in_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.rouletteitems', verbose_name='Выполняемое задание'),
        ),
    ]
