# Generated by Django 4.1.5 on 2023-02-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0010_alter_roulettehistory_completed_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roulettehistory',
            name='completed_stage',
        ),
        migrations.AddField(
            model_name='roulettehistory',
            name='is_completed_quest',
            field=models.BooleanField(default=True, verbose_name='Квест выполнен'),
        ),
    ]
